--- 
org: 
  cloudfoundry: 
    demo: 
      browser: 
        zipkin: 
          enabled: false
spring: 
  application: 
    name: browser
  sleuth: 
    sampler: 
      percentage: 1.0
  profiles:
    active: no-hystrix
security:
  basic:
    enabled: false
